# Generated by Django 6.0.6 on 2026-07-04 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_jobs_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user',
            field=models.PositiveIntegerField(),
        ),
    ]
